/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    MColorPicker: typeof import('ming-UI')['MColorPicker']
    MControlPanel: typeof import('ming-UI')['MControlPanel']
    MIcon: typeof import('ming-UI')['MIcon']
    Mute: typeof import('ming-UI')['Mute']
  }
}
