export { default as MButton } from './button'
export { default as MInput } from './input'
export { default as MTooltip } from './tooltip'
export { default as MTable } from './table'
// export { default as MColorPicker, openColorPicker } from './color-picker'
export { default as MColorPicker } from './color-picker'
export { default as MControlPanel } from './control-panel'
